(ns temci.constants)


;; timestamp scheduler addresses per network
(defn tSchedulerAddress [network-id]
  (case network-id
    "1" "0x09e0c54ed4cffca45d691d5eb7b976d650f5904c"
    "2" "0x09e0c54ed4cffca45d691d5eb7b976d650f5904c"
    "3" "0xaba1c9637f79ae219a6aa0e93b47d5a6b91eb7de"
    "4" "0xd29c566ae1842cac0248401a73b1043c76871686"
    "42" "0x44b28e47fe781eabf8095a2a21449a82a635745b"
    ""))

(def timestampAbi (.parse js/JSON "[{\"constant\":false,\"inputs\":[{\"name\":\"_toAddress\",\"type\":\"address\"},{\"name\":\"_callData\",\"type\":\"bytes\"},{\"name\":\"_uintArgs\",\"type\":\"uint256[8]\"}],\"name\":\"schedule\",\"outputs\":[{\"name\":\"newRequest\",\"type\":\"address\"}],\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"temporalUnit\",\"outputs\":[{\"name\":\"\",\"type\":\"uint8\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"feeRecipient\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[{\"name\":\"_bounty\",\"type\":\"uint256\"},{\"name\":\"_fee\",\"type\":\"uint256\"},{\"name\":\"_callGas\",\"type\":\"uint256\"},{\"name\":\"_callValue\",\"type\":\"uint256\"},{\"name\":\"_gasPrice\",\"type\":\"uint256\"}],\"name\":\"computeEndowment\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"factoryAddress\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"name\":\"_factoryAddress\",\"type\":\"address\"},{\"name\":\"_feeRecipient\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"fallback\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"name\":\"request\",\"type\":\"address\"}],\"name\":\"NewRequest\",\"type\":\"event\"}]"))

(def blockAbi (.parse js/JSON "[{\"constant\":false,\"inputs\":[{\"name\":\"_toAddress\",\"type\":\"address\"},{\"name\":\"_callData\",\"type\":\"bytes\"},{\"name\":\"_uintArgs\",\"type\":\"uint256[8]\"}],\"name\":\"schedule\",\"outputs\":[{\"name\":\"newRequest\",\"type\":\"address\"}],\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"temporalUnit\",\"outputs\":[{\"name\":\"\",\"type\":\"uint8\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"feeRecipient\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[{\"name\":\"_bounty\",\"type\":\"uint256\"},{\"name\":\"_fee\",\"type\":\"uint256\"},{\"name\":\"_callGas\",\"type\":\"uint256\"},{\"name\":\"_callValue\",\"type\":\"uint256\"},{\"name\":\"_gasPrice\",\"type\":\"uint256\"}],\"name\":\"computeEndowment\",\"outputs\":[{\"name\":\"\",\"type\":\"uint256\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"factoryAddress\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"name\":\"_factoryAddress\",\"type\":\"address\"},{\"name\":\"_feeRecipient\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"fallback\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"name\":\"request\",\"type\":\"address\"}],\"name\":\"NewRequest\",\"type\":\"event\"}]
"))
